{{- if and .Values.rbac.create (eq .Values.clusterRole.create true) -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "helm-operator.clusterRoleName" . }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
{{- end -}}
{{- if and .Values.rbac.create -}}
{{- if or .Values.clusterRole.create .Values.clusterRole.exist -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  {{- if and .Values.clusterRole.exist }}
  name: {{ template "helm-operator.fullname" . }}
  {{- else }}
  name: {{ template "helm-operator.clusterRoleName" . }}
  {{- end }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if and .Values.clusterRole.exist }}
  name: {{ .Values.clusterRole.name }}
  {{- else }}
  name: {{ template "helm-operator.clusterRoleName" . }}
  {{- end }}
subjects:
  - name: {{ template "helm-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
---
{{- end -}}
{{- end -}}